services:

  marrquee:
    container_name: marrquee
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
      - PLEX_BASE_URL=${PLEX_BASE_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
