services:

  marrquee:
    container_name: marrquee
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - marrquee-storage:/data
    environment:
      - DEBUG=true
      - PLEX_BASE_URL=${PLEX_BASE_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
    ports:
      - "1989:1989"
    stdin_open: true
    tty: true

volumes:
  marrquee-storage:
